# -*- coding: utf-8 -*-
"""superstore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfZoHPDnjFS9b9ZlqpvNXSnksLC_0ICj
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/samplesuperstore.csv.xls")

print("First 5 Rows:")
display(df.head())

print("\nDataset Information:")
df.info()


print("\nStatistical Description:")
display(df.describe())

print("\nDataset Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

print("\nDate Columns After Conversion:")
print(df[['Order Date', 'Ship Date']].dtypes)

categorical_columns = ['Category', 'Sub-Category', 'Segment']

for column in categorical_columns:
    df[column] = df[column].astype(str).str.strip().str.title()

print("\nCleaned Categorical Data:")
display(df[categorical_columns].head())

print("\nNumber of Duplicate Rows:")
print(df.duplicated().sum())

df = df.drop_duplicates()

numerical_columns = df.select_dtypes(include=np.number).columns

print("\nNumerical Columns:")
print(numerical_columns.tolist())

print("\nSummary Statistics for Numerical Attributes:")
display(df[numerical_columns].describe())

print("\nTotal Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
print("Minimum Sales:", df['Sales'].min())
print("Maximum Sales:", df['Sales'].max())

if 'Profit' in df.columns:
    print("\nTotal Profit:", df['Profit'].sum())
    print("Average Profit:", df['Profit'].mean())
    print("Minimum Profit:", df['Profit'].min())
    print("Maximum Profit:", df['Profit'].max())

print("\nCategory Counts:")
display(df['Category'].value_counts())

print("\nSub-Category Counts:")
display(df['Sub-Category'].value_counts())

print("\nSegment Counts:")
display(df['Segment'].value_counts())

print("\nCleaned Dataset:")
display(df.head())

print("\nFinal Dataset Information:")
df.info()



